### ISSUE TITLE
Prototype polution

### ISSUE THREAD

**Issue by schimini** [gsipos/rxjs-ratelimit#1]
Hi, just wanted to say this is a cool script and it would be a fine addition to the rxjs world. 

The only thing relevant I see that could be better ( I know this is 4 years old ) would be if the prototype was unchanged. And just because why not make it into a library? Js / ts is known for it, one more wouldn't hurt :)

**Comment by gsipos** [comment]
Hi!
Yeah, I haven't worked with rxjs in a couple of years, so I suspect some things changed in rxjs as well. I'll need to dive into it, see what is the current way of adding stuff to rxjs. 
But yeah overall this shouldn't be a big effort to change this into a lib/npm package.
Do you know a similar rxjs lib that I could use as a prior art?

**Comment by gsipos** [comment]
I found this package: https://www.npmjs.com/package/rxjs-ratelimit-operator
It seems it is doing the same functionality with the newer rxjs pipe api. Does this help you?

**Comment by schimini** [comment]
@gsipos hi,
I don't even know how I missed that. That library looks good yeah. Thanks!
